# Generated by Django 5.1.7 on 2025-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('load_factor', models.FloatField(default=0.0)),
            ],
            options={
                'indexes': [models.Index(fields=['api_key', 'load_factor'], name='task2_agenc_api_key_14ea5a_idx')],
            },
        ),
    ]
